name: flutter_share
description: Simple way to share message, links or files from your flutter app for Android and IOS (Enter to see some gifs).
version: 2.0.0
homepage: https://github.com/lubritto/flutter_share

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.fluttershare
        pluginClass: FlutterSharePlugin
        dartPluginClass: FlutterShareMethod
      ios:
        pluginClass: FlutterSharePlugin
        dartPluginClass: FlutterShareMethod

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'